In [28]:
import pandas as pd

In [29]:
hnp = pd.read_csv('./extracted/hnp_stats_csv/HNP_StatsData.csv')

In [30]:
hnp

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Africa Eastern and Southern,AFE,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,140.120535,140.594564,141.128109,141.32344,141.50816,141.668896,...,103.391461,101.541782,99.719799,97.916601,96.146492,94.695223,93.231944,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Adults (ages 15+) and children (0-14 years) li...,SH.HIV.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Africa Eastern and Southern,AFE,Adults (ages 15+) and children (ages 0-14) new...,SH.HIV.INCD.TL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Eastern and Southern,AFE,Adults (ages 15+) living with HIV,SH.DYN.AIDS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Africa Eastern and Southern,AFE,Adults (ages 15-49) newly infected with HIV,SH.HIV.INCD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121557,Zimbabwe,ZWE,Wanted fertility rate (births per woman),SP.DYN.WFRT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121558,Zimbabwe,ZWE,Women who were first married by age 15 (% of w...,SP.M15.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.700000,NaN,NaN,NaN,5.418352,NaN,NaN,NaN
121559,Zimbabwe,ZWE,Women who were first married by age 18 (% of w...,SP.M18.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33.500000,32.400000,NaN,NaN,NaN,33.658057,NaN,NaN,NaN
121560,Zimbabwe,ZWE,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,59.200000,59.400000,59.500000,59.700000,59.900000,60.000000,60.200000,60.4,NaN,NaN
121561,Zimbabwe,ZWE,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,NaN,NaN,NaN,NaN,NaN,NaN,...,18000.000000,17000.000000,15000.000000,14000.000000,12000.000000,9700.000000,9600.000000,7500.0,NaN,NaN

In [31]:
len(hnp['Indicator Code'].unique())

457

In [32]:
hnps = pd.read_csv('./extracted/hnp_stats_csv/HNP_StatsSeries.csv')

In [34]:
hnps['Topic'].unique()

array(['Public Sector: Policy & institutions', 'Background: Economy',
       'Background: Education', 'Non-communicable diseases', 'Nutrition',
       'HIV/AIDS', 'Population dynamics: Other demographic indicators',
       'Cause of deaths',
       'Population dynamics: Other demographic Indicators',
       'Reproductive health', 'Water and sanitation', nan, 'Immunization',
       'Medical resources and usage', 'Infectious diseases',
       'Health financing', 'Background: Poverty',
       'Background: Labor force', 'Population dynamics', 'Background',
       'Population dynamics: Population by age group',
       'Population dynamics: Population'], dtype=object)

In [20]:
nd = pd.read_csv('./extracted/natural_disasters/EMDAT_1900-2021_NatDis.csv')

In [21]:
nd.columns

Index(['Dis No', 'Year', 'Seq', 'Disaster Group', 'Disaster Subgroup',
       'Disaster Type', 'Disaster Subtype', 'Disaster Subsubtype',
       'Event Name', 'Entry Criteria', 'Country', 'ISO', 'Region', 'Continent',
       'Location', 'Origin', 'Associated Dis', 'Associated Dis2',
       'OFDA Response', 'Appeal', 'Declaration', 'Aid Contribution',
       'Dis Mag Value', 'Dis Mag Scale', 'Latitude', 'Longitude', 'Local Time',
       'River Basin', 'Start Year', 'Start Month', 'Start Day', 'End Year',
       'End Month', 'End Day', 'Total Deaths', 'No Injured', 'No Affected',
       'No Homeless', 'Total Affected', 'Reconstruction Costs ('000 US$)',
       'Insured Damages ('000 US$)', 'Total Damages ('000 US$)', 'CPI'],
      dtype='object')