In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns
import dtale as dt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from xgboost import XGBClassifier
pd.options.plotting.backend = "plotly"

In [6]:
hnp = pd.read_csv('./extracted/hnp_stats_csv/HNP_StatsData.csv')
pe = pd.read_csv('./extracted/gdelt/gdelt_conflict_1_0.csv')
hnpc = pd.read_csv('./extracted/hnp_stats_csv/HNP_StatsCountry.csv')
hdi = pd.read_csv('./extracted/hdi_country.csv')

In [13]:
hnpc_keep = hnpc[['Country Code', 'Table Name', 'Long Name', 'Region', 'Currency Unit', 'Income Group', 'System of trade', 'Government Accounting concept', 'Lending category']]

In [14]:
hnp
columns = []
data = []
for country in hnp['Country Name'].unqiue():
    row = []
    for indicator in hnp['Indicator Name'].unique():

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Africa Eastern and Southern,AFE,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,140.120535,140.594564,141.128109,141.32344,141.50816,141.668896,...,103.391461,101.541782,99.719799,97.916601,96.146492,94.695223,93.231944,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Adults (ages 15+) and children (0-14 years) li...,SH.HIV.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Africa Eastern and Southern,AFE,Adults (ages 15+) and children (ages 0-14) new...,SH.HIV.INCD.TL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Eastern and Southern,AFE,Adults (ages 15+) living with HIV,SH.DYN.AIDS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Africa Eastern and Southern,AFE,Adults (ages 15-49) newly infected with HIV,SH.HIV.INCD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121557,Zimbabwe,ZWE,Wanted fertility rate (births per woman),SP.DYN.WFRT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121558,Zimbabwe,ZWE,Women who were first married by age 15 (% of w...,SP.M15.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.700000,NaN,NaN,NaN,5.418352,NaN,NaN,NaN
121559,Zimbabwe,ZWE,Women who were first married by age 18 (% of w...,SP.M18.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33.500000,32.400000,NaN,NaN,NaN,33.658057,NaN,NaN,NaN
121560,Zimbabwe,ZWE,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,59.200000,59.400000,59.500000,59.700000,59.900000,60.000000,60.200000,60.4,NaN,NaN
121561,Zimbabwe,ZWE,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,NaN,NaN,NaN,NaN,NaN,NaN,...,18000.000000,17000.000000,15000.000000,14000.000000,12000.000000,9700.000000,9600.000000,7500.0,NaN,NaN

In [18]:
hnp[(hnp['Country Name'] == 'Zimbabwe') & (hnp['Indicator Name'] == 'Young people (ages 15-24) newly infected with HIV')]['2020'].value

AttributeError: 'Series' object has no attribute 'value'